name: changelog

ide:
  intellij: true

packages:
  - packages/**

scripts:
  analyze:
    run: melos exec -c 1 -- "dart analyze . --fatal-infos"
    description: Run dart analyzer in a specific package.

  format:
    run: melos exec -c 1 -- "dart format -o write ."

  test:
    description: Run tests in a specific package.
    # TODO(Salakar) 'dart pub get' is necessary for the 'melos' package as we're using it on itself
    run: melos exec --concurrency=1 -- "dart pub get && dart pub run test"
    select-package:
      dir-exists:
        - "test/"
    # This tells Melos tests to ignore env variables passed to tests from `melos run test`
    # as they could change the behaviour of how tests filter packages.
    env:
      MELOS_TEST: true

  gen:
    run: melos exec --concurrency=1 -- "dart run build_runner build"
    select-package:
        ignore:
          - "*changelog-lib*"