name: changelog_lib
description: A starting point for Dart libraries or applications.
version: 0.0.1-beta.1
homepage: https://github.com/vincenzopalazzo/changelog.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
