name: changelog.dart publish to to Pub.dev

on:
  release:
    types: [created]
  pull_request:
  workflow_run:
    workflows:
      - "changelog.dart sanity code base"
      - "changelog.dar test"
    branches: [ main ]
    types:
      - completed

jobs:
  publishing_lib:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2 # required!

      - name: 'changelog-lib publish to to Pub.dev'
        uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          flutter: false
          skipTests: true
          dryRunOnly: ${{ github.event_name != 'release' }}
          relativePath: './packages/changelog-lib/'
  publishing_cmd:
    runs-on: ubuntu-latest
    needs:
      - publishing_lib
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2 # required!

      - name: 'changelog-cmd publish to to Pub.dev'
        uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          flutter: false
          skipTests: true
          dryRunOnly: ${{ github.event_name != 'release' }}
          relativePath: './packages/changelog-cmd/'
